name: StatsAPI
version: '${project.version}'
main: dev.gomorrha.statspi.StatsAPI
api-version: 1.20
authors: [ Gomorrha, Melays ]
description: Melays StatsAPI in Minecraft 1.20.1
website: https://gomorrha.dev
